#!/usr/bin/env python

def main(lines):
    lines = unique(lines)

    lines.sort()

    return lines


def unique(lines):
    return list(set(lines))

if __name__ == '__main__':
    import os
    import argparse

    parser = argparse.ArgumentParser()

    parser.add_argument('-f', '--file', dest='filename')

    args = parser.parse_args()
    filename = args.filename

    def error(message):
        print(message)
        exit(1)

    if filename is None or type(filename) is not str:
        error("Please add -f or --file to point to a file")

    if not os.path.exists(filename):
        error("{} does not exist.".format(filename))
    if not os.path.isfile(filename):
        error("{} is not a file.".format(filename))

    with open(filename) as f:
        trace_lines = f.readlines()

    if len(trace_lines) == 0:
        error("File is empty.")

    lines = main(trace_lines)

    root, ext = os.path.splitext(filename)

    with open(root + "-simplified" + ext, 'w') as f:
        f.writelines(lines)
