#!/usr/bin/env python3
"""Generates themes.yaml from a list of picked Ghostty themes.

Edit PICKED_THEMES and LAST_REVIEWED below, then re-run.
Reads background colors from Ghostty's bundled theme files,
classifies light/dark, and labels the dominant bg color.
"""

from pathlib import Path

THEMES_DIR = Path("/Applications/Ghostty.app/Contents/Resources/ghostty/themes")
SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT = SCRIPT_DIR / "themes.yaml"
CLASSIFIED_OUTPUT = SCRIPT_DIR / "classified-themes.yaml"
ALL_THEMES_FILE = SCRIPT_DIR / "all-themes.txt"

# --- Review progress ---
LAST_REVIEWED = "Coffee Theme"

# --- Picked themes ---
PICKED_THEMES = [
    "Afterglow",
    "Andromeda",
    "Apple Classic",
    "Arcoiris",
    "Ardoise",
    "Arthur",
    "Atom One Dark",
    "Aurora",
    "Ayu Mirage",
    "Belafonte Day",
    "Blazer",
    "Blue Dolphin",
    "Bluloco Dark",
    "Bluloco Light",
    "branch",
    "Breadog",
    "Breeze",
    "Broadcast",
    "Builtin Tango Light",
    "Catppuccin Frappe",
    "Catppuccin Latte",
    "Catppuccin Macchiato",
    "Catppuccin Mocha",
    "Chalk",
    "Chalkboard",
    "Chester",
    "Coffee Theme",
]


def parse_bg(theme_name: str) -> str | None:
    path = THEMES_DIR / theme_name
    if not path.exists():
        print(f"WARNING: theme not found: {theme_name}")
        return None
    for line in path.read_text().splitlines():
        if line.startswith("background"):
            return line.split("=", 1)[1].strip()
    return None


def luminance(hex_color: str) -> float:
    h = hex_color.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return 0.299 * r + 0.587 * g + 0.114 * b


def classify(hex_color: str) -> tuple[str, str]:
    h = hex_color.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    lum = luminance(hex_color)

    mode = "light" if lum > 128 else "dark"

    if lum > 200:
        if r > 240 and g > 240 and b > 240:
            label = "white"
        elif r > g > b:
            label = "cream"
        else:
            label = "light gray"
    elif lum > 140:
        label = "tan" if r > g > b else "light gray"
    elif lum < 40:
        if b > r and b > g:
            label = "dark blue"
        elif r > g > b and (r - b) > 15:
            label = "dark brown"
        else:
            label = "black"
    else:
        if b > r + 15 and b > g + 15:
            label = "blue"
        elif r < 60 and g > 80 and b > 100:
            label = "teal"
        elif b > r and b > g:
            label = "dark blue"
        else:
            label = "dark gray"

    return mode, label


def reviewed_count() -> tuple[int, int]:
    if not ALL_THEMES_FILE.exists():
        return 0, 0
    lines = ALL_THEMES_FILE.read_text().splitlines()
    total = len(lines)
    count = 0
    for name in lines:
        count += 1
        if name == LAST_REVIEWED:
            break
    return count, total


def main():
    count, total = reviewed_count()

    dark_themes = []
    light_themes = []

    for theme in PICKED_THEMES:
        bg = parse_bg(theme)
        if bg is None:
            continue
        mode, label = classify(bg)
        entry = {"name": theme, "background": bg, "bg_color": label}
        if mode == "dark":
            dark_themes.append(entry)
        else:
            light_themes.append(entry)

    lines = [
        "# Auto-generated by generate-themes-yaml.py",
        "# Re-run after editing PICKED_THEMES or LAST_REVIEWED.",
        "",
        "review:",
        f'  last_reviewed: "{LAST_REVIEWED}"',
        f"  reviewed_count: {count}",
        f"  total_count: {total}",
        "",
        "starred:",
        "",
        "dark:",
    ]
    for t in dark_themes:
        lines.append(f'  - name: "{t["name"]}"')
        lines.append(f'    background: "{t["background"]}"')
        lines.append(f"    bg_color: {t['bg_color']}")
    lines.append("")
    lines.append("light:")
    for t in light_themes:
        lines.append(f'  - name: "{t["name"]}"')
        lines.append(f'    background: "{t["background"]}"')
        lines.append(f"    bg_color: {t['bg_color']}")
    lines.append("")

    OUTPUT.write_text("\n".join(lines))
    print(f"Written to {OUTPUT}")
    print(f"Review progress: {count} / {total} themes reviewed")

    # Generate classified-themes.yaml for all themes
    generate_classified()


def generate_classified():
    """Classify all themes from all-themes.txt and write classified-themes.yaml."""
    if not ALL_THEMES_FILE.exists():
        print("No all-themes.txt found, skipping classification.")
        return

    all_names = ALL_THEMES_FILE.read_text().splitlines()
    classified = {}
    skipped = 0
    for name in all_names:
        bg = parse_bg(name)
        if bg is None:
            skipped += 1
            continue
        mode, _ = classify(bg)
        classified[name] = mode

    out_lines = ["# Auto-generated. Maps theme name -> mode."]
    for name in sorted(classified.keys(), key=str.lower):
        out_lines.append(f"{name}: {classified[name]}")
    out_lines.append("")

    CLASSIFIED_OUTPUT.write_text("\n".join(out_lines))
    print(f"Written {len(classified)} classifications to {CLASSIFIED_OUTPUT}")
    if skipped:
        print(f"  ({skipped} themes skipped, no background found)")


if __name__ == "__main__":
    main()
