#!/usr/bin/env python3
"""Generates themes.yaml from a list of picked Ghostty themes.

Edit PICKED_THEMES and LAST_REVIEWED below, then re-run.
Reads background colors from Ghostty's bundled theme files,
classifies light/dark, and labels the dominant bg color.
"""

import sys
from pathlib import Path

THEMES_DIR = Path("/Applications/Ghostty.app/Contents/Resources/ghostty/themes")
SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT = SCRIPT_DIR / "themes.yaml"
CLASSIFIED_OUTPUT = SCRIPT_DIR / "classified-themes.yaml"
ALL_THEMES_FILE = SCRIPT_DIR / "all-themes.txt"

# Ensure theme_picker is importable if run directly
sys.path.insert(0, str(SCRIPT_DIR))

from theme_picker.data import parse_bg, classify, generate_classified

# --- Review progress ---
LAST_REVIEWED = "Coffee Theme"

# --- Picked themes ---
PICKED_THEMES = [
    "Afterglow",
    "Andromeda",
    "Apple Classic",
    "Arcoiris",
    "Ardoise",
    "Arthur",
    "Atom One Dark",
    "Aurora",
    "Ayu Mirage",
    "Belafonte Day",
    "Blazer",
    "Blue Dolphin",
    "Bluloco Dark",
    "Bluloco Light",
    "branch",
    "Breadog",
    "Breeze",
    "Broadcast",
    "Builtin Tango Light",
    "Catppuccin Frappe",
    "Catppuccin Latte",
    "Catppuccin Macchiato",
    "Catppuccin Mocha",
    "Chalk",
    "Chalkboard",
    "Chester",
    "Coffee Theme",
]



def reviewed_count() -> tuple[int, int]:
    if not ALL_THEMES_FILE.exists():
        return 0, 0
    lines = ALL_THEMES_FILE.read_text().splitlines()
    total = len(lines)
    count = 0
    for name in lines:
        count += 1
        if name == LAST_REVIEWED:
            break
    return count, total


def main():
    count, total = reviewed_count()

    dark_themes = []
    light_themes = []

    for theme in PICKED_THEMES:
        bg = parse_bg(theme)
        if bg is None:
            continue
        mode, label = classify(bg)
        entry = {"name": theme, "background": bg, "bg_color": label}
        if mode == "dark":
            dark_themes.append(entry)
        else:
            light_themes.append(entry)

    lines = [
        "# Auto-generated by generate-themes-yaml.py",
        "# Re-run after editing PICKED_THEMES or LAST_REVIEWED.",
        "",
        "review:",
        f'  last_reviewed: "{LAST_REVIEWED}"',
        f"  reviewed_count: {count}",
        f"  total_count: {total}",
        "",
        "starred:",
        "",
        "dark:",
    ]
    for t in dark_themes:
        lines.append(f'  - name: "{t["name"]}"')
        lines.append(f'    background: "{t["background"]}"')
        lines.append(f"    bg_color: {t['bg_color']}")
    lines.append("")
    lines.append("light:")
    for t in light_themes:
        lines.append(f'  - name: "{t["name"]}"')
        lines.append(f'    background: "{t["background"]}"')
        lines.append(f"    bg_color: {t['bg_color']}")
    lines.append("")

    OUTPUT.write_text("\n".join(lines))
    print(f"Written to {OUTPUT}")
    print(f"Review progress: {count} / {total} themes reviewed")

    # Generate classified-themes.yaml for all themes
    generate_classified()



if __name__ == "__main__":
    main()
